### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(GetStartedContent)
add_subdirectory(GetStarted)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	GetStartedContentplugin
	GetStartedplugin)